### PR TITLE
JENKINS-42475 Add support for pipeline in SbtInstallation

### PR DESCRIPTION
**Pull request by froque**
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] ~~Link to relevant pull requests, esp. upstream and downstream changes~~
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jglick** [comment]
This would not necessarily be a good idea. https://github.com/jenkins-infra/jenkins.io/pull/7693 What does this plugin actually do that you could not do just as easily without any special plugin? https://github.com/jenkinsci/sbt-plugin/blob/d60f4eb9d47f8e5aa5643721432954eb72bd8aa6/src/main/java/org/jvnet/hudson/plugins/SbtPluginBuilder.java#L104-L105 does not look particularly helpful. https://github.com/jenkinsci/sbt-plugin/blob/d60f4eb9d47f8e5aa5643721432954eb72bd8aa6/src/main/java/org/jvnet/hudson/plugins/SbtPluginBuilder.java#L343 perhaps, but you can also use this with the `tool` step if you really want (though these days I would advise using container-based builds and ignoring the tool system).

**Comment by froque** [comment]
The idea here is to simplify this 
```groovy
    tools {
      jdk 'java-1.8.0'
    }

    environment {
      SBT_HOME = tool name: '1.10.5', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'
      PATH = "${env.SBT_HOME}/bin:${env.PATH}"
    }
``` 
into this:
```groovy
    tools {
      jdk 'java-1.8.0'
      sbt '1.10.5'
    }
```

@jglick do you object this change as is ? What do you propose instead ?

**Comment by jglick** [comment]
If you are only touching the tool installation, fine. https://github.com/jenkinsci/sbt-plugin/blob/b350267469ec7b844e7e5a56ff83a8519ada9509/src/main/java/org/jvnet/hudson/plugins/SbtPluginBuilder.java#L61 means that the build step will continue to support only non-Pipeline projects. The PR title may mislead readers.

BTW

```groovy
PATH = "${env.SBT_HOME}/bin:${env.PATH}"
```

can probably be written more legibly as

```groovy
PATH+SBT = "$SBT_HOME/bin"
```

(this certainly works with Scripted syntax and `withEnv` but I am less familiar with Declarative) and the

```groovy
SBT_HOME = tool name: '1.10.5', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'
```

could be simplified to e.g.

```groovy
SBT_HOME = tool name: '1.10.5', type: 'sbt'
```

with the addition of a `@Symbol`.

**Comment by froque** [comment]
> The PR title may mislead readers.

Yeah, that is right, Updated.

Thanks for the feedback.

**Pull request merged**
