### PR TITLE
allows build in subdir

### PR DESCRIPTION
**Pull request by michaelmwu**
I have some projects where the sbt project directory is not the main workspace directory. So I added a little configuration bit so sbt can build in a subdirectory of the project.

### CODE REVIEW

**Comment by nemoo** [comment]
How does one configure the subdirectory in the Jenkins job?

**Comment by kamatsuoka** [comment]
@nemoo Click on the Advanced button for the sub-directory path form field.

**Comment by AbacusIntegrationPlatform** [comment]
I am trying to add the sub-directory path using an environment variable. But it's not resolving. Is there a way I can configure my sub-directory path using a build parameter variable?

Example - ${DIRECTORY_PATH}

**Comment by jason-koppel-avlino** [comment]
> 
> 
> I am trying to add the sub-directory path using an environment variable. But it's not resolving. Is there a way I can configure my sub-directory path using a build parameter variable?
> 
> Example - ${DIRECTORY_PATH}

I have this same problem, does anyone know how to fix this?

**Pull request merged**
