### PR TITLE
Updated broken links

### PR DESCRIPTION
**Pull request by ctataryn**

### CODE REVIEW

**Comment by ctataryn** [comment]
Hi @uzilan / @wolfg1969, are you folks still accepting PRs for this plugin?

**Comment by uzilan** [comment]
Haven't touched this plugin for quite a while. You want to join in and take responsibility?

**Comment by ctataryn** [comment]
@uzilan Certainly, thank you. Just let me know if I have to do anything on my side.

**Comment by uzilan** [comment]
@ctataryn I've added you as a collaborator. Please feel free to update the project.

**Comment by ctataryn** [comment]
@uzilan Thanks, would you be able to take me through the release process for the plugin?  Or does the CI job do that automatically when merged?

**Comment by uzilan** [comment]
@ctataryn It's...been a while. Can't remember really. maybe this can help: https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkins-ci.org

**Pull request merged**
